neuro-inc/cookiecutter-neuro-project

README.md
{{cookiecutter.project_slug}}/Makefile
{{cookiecutter.project_slug}}/README.md

1. Add make target sorting by name in `make help`
2. Replace understore with dash in target names (fixes #4)
3. Remove empty line in the Makefile
4. Add `--browse` to `make tensorboard` and `make filebrowser` targets

Several minor fixes

---

cookiecutter.json
{{cookiecutter.project_slug}}/Makefile
{{cookiecutter.project_slug}}/README.md

Set default package name to `modules`

---

{{cookiecutter.project_slug}}/Makefile

Replace "storage load" with "cp"

---

cookiecutter.json
{{cookiecutter.project_slug}}/LICENSE

Add license selector

---

{{cookiecutter.project_slug}}/Makefile

otherwise it hangs with the question:
```
The authenticity of host 'ssh-auth-dev.neu.ro (35.188.193.235)' can't be established.
ECDSA key fingerprint is 06:14:c5:6e:31:1c:4e:e7:36:90:7c:f8:d3:eb:89:cd.
Are you sure you want to continue connecting (yes/no)? 
```

Fix Makefile: `neuro exec --no-key-check`

---

{{cookiecutter.project_slug}}/Makefile

Closes https://github.com/neuromation/template-base-image/issues/5

Set PLATFORMAPI_SERVICE_HOST to dummy value

---

{{cookiecutter.project_slug}}/Makefile

Fix jupyter issues

---

{{cookiecutter.project_slug}}/Makefile

When working on e2e tests, I faced the problem of both pip and apt being too noisy by default, see https://circleci.com/gh/neuromation/cookiecutter-neuro-project/67

Fix Makefile: Install packages in less noisy way

---

{{cookiecutter.project_slug}}/Makefile

Closes #45
Note `make upload-data` uses additional option: `--progress`

Fix `cp` commands

---

{{cookiecutter.project_slug}}/Makefile

Extract training command to a variable

---

{{cookiecutter.project_slug}}/.gitignore

Add data/ to .gitignore

---

cookiecutter.json
{{cookiecutter.project_slug}}/LICENSE

Refine template parameters / Simplify license

---

tests/e2e/configuration.py
tests/e2e/conftest.py
tests/e2e/test_e2e_template.py

Keep notebooks/ in git correctly

---

.circleci/config.yml

Add log artifacts on staging too

---

{{cookiecutter.project_slug}}/Makefile

Fixes https://github.com/neuromation/cookiecutter-neuro-project/issues/71

Mute neuro-kill errors

---

Makefile
tests/e2e/utils.py

1. do not abort on 1 failure (for both dev and staging allow 2 reruns)
2. print minimal traceback for dev

Change pytest options

---

{{cookiecutter.project_slug}}/Makefile

Add --no-tty

---

{{cookiecutter.project_slug}}/Makefile

Use full command for neuro rm

---

tests/e2e/conftest.py
tests/e2e/test_e2e_template.py
{{cookiecutter.project_slug}}/Makefile

Closes #102 
I did not remove `--detach` from `make setup` though. Let me know if you think that's necessary.

Remove --detach for most make targets

---

Makefile
cookiecutter.json
hooks/pre_gen_project.py
setup.cfg
tests/e2e/configuration.py
tests/unit/test_bake_project.py
{{cookiecutter.project_slug}}/Makefile

Validate project slug via pre-hook

---

{{cookiecutter.project_slug}}/Makefile

Remove --network-timout

---

{{cookiecutter.project_slug}}/requirements.txt

Remove version numbers from requirements.txt

---

cookiecutter.json
hooks/pre_gen_project.py
tests/e2e/configuration.py
tests/e2e/test_e2e_template.py
{{cookiecutter.project_slug}}/Makefile
{{cookiecutter.project_slug}}/README.md

Should close the following issues: #88, #96, #86, #66, #87.

[WIP] Simplification

---

{{cookiecutter.project_slug}}/Makefile

Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/153 as a continuation of https://github.com/neuromation/template-base-image/pull/33/

Get rid of `-e PLATFORMAPI_SERVICE_HOST="."`

---

tests/e2e/configuration.py
tests/e2e/test_e2e_template.py

Due to the problems with tests https://github.com/neuromation/cookiecutter-neuro-project/issues/162, the tests didn't fail however the problem exist.

Fix test checking code availability from the notebooks

---

{{cookiecutter.project_slug}}/Makefile

Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/160

Fix target: `make setup-local`

---

.circleci/config.yml

FYI: Results will be posted to Slack's channel `#template-nightly-testing`

Nightly builds

---

tests/e2e/configuration.py
tests/e2e/helpers/runners.py
tests/e2e/test_e2e_template.py

Tests cleanup

---

Makefile
tests/e2e/cleanup.sh
tests/e2e/configuration.py
tests/e2e/conftest.py
tests/e2e/test_e2e_template.py

Allow project folder reuse

---

tests/e2e/helpers/runners.py
tests/e2e/test_e2e_template.py

Exit code tracking

---

.circleci/config.yml

for tracking the cluster's liveability

Run e2e tests hourly

---

Makefile
tests/e2e/cleanup.sh
tests/e2e/conftest.py

Fix `cleanup.sh` broken in https://github.com/neuromation/cookiecutter-neuro-project/pull/165/

Revert changes to cleanup.sh

---

tests/e2e/helpers/runners.py
tests/e2e/test_e2e_template.py

[tests] Add default error patterns everywhere

---

tests/e2e/test_e2e_template.py

no functional difference, fix name only

[tests] Minor: fix step name

---

tests/e2e/conftest.py
tests/e2e/test_e2e_template.py

closes https://github.com/neuromation/cookiecutter-neuro-project/issues/217

[tests] Consider --environment when choosing timeout

---

{{cookiecutter.project_slug}}/Makefile

close https://github.com/neuromation/cookiecutter-neuro-project/issues/181

[Makefile] Make upload-all / kill-all

---

tests/e2e/test_e2e_template.py
{{cookiecutter.project_slug}}/Makefile

as requested here: https://docs.google.com/document/d/13c_eYG2v4wNnp9RIhE_gXCSTvEw_i_HQzK7djEsSOjw/

[Makefile] Rename target `training` -> `train`

---

{{cookiecutter.project_slug}}/Makefile
{{cookiecutter.project_slug}}/notebooks/Untitled.ipynb

idea: from https://docs.google.com/document/d/13c_eYG2v4wNnp9RIhE_gXCSTvEw_i_HQzK7djEsSOjw/

[Makefile] Better way to make code available from notebooks

---

{{cookiecutter.project_slug}}/Makefile

requested in https://docs.google.com/document/d/13c_eYG2v4wNnp9RIhE_gXCSTvEw_i_HQzK7djEsSOjw/

[Makefile] Add new target: make kill-setup

---

{{cookiecutter.project_slug}}/Makefile

Follow-up of https://github.com/neuromation/cookiecutter-neuro-project/pull/199: `make clean` -> `make clean-all`

[Makefile] Make clean-all

---

tests/e2e/configuration.py
tests/e2e/conftest.py
tests/e2e/helpers/runners.py
tests/e2e/helpers/utils.py
tests/e2e/test_e2e_template.py
{{cookiecutter.project_slug}}/Makefile
{{cookiecutter.project_slug}}/README.md

Yesterday, after merging 2 bugs with green tests, I realized that Template test coverage needs to be improved. This PR covers *all* public commands with tests. 
Also, added some info on `TRAINING_MODEL` to `Readme.md`

[tests][Readme] All remaining tests!

---

tests/e2e/helpers/runners.py
tests/e2e/test_e2e_template.py

Fix of exit-code check introduced in https://github.com/neuromation/cookiecutter-neuro-project/pull/175. Will close https://github.com/neuromation/cookiecutter-neuro-project/issues/162

[tests] Fix exit code check

---

.circleci/config.yml
tests/e2e/cleanup.sh
tests/e2e/conftest.py

Fix e2e cleanup in https://circleci.com/gh/neuromation/cookiecutter-neuro-project/1170

[tests] Fix cleanup: outdated version of `neuro`

---

tests/e2e/configuration.py
tests/e2e/test_e2e_template.py
{{cookiecutter.project_slug}}/Makefile

Workaround for this problem: https://github.com/neuromation/platform-client-python/issues/1228

[Makefile] Make targets `connect-*` work!

---

tests/e2e/helpers/runners.py
tests/e2e/test_e2e_template.py
{{cookiecutter.project_slug}}/Makefile

closes https://github.com/neuromation/cookiecutter-neuro-project/issues/212

Require `make setup` for each target

---

{{cookiecutter.project_slug}}/Makefile

as requested in https://docs.google.com/document/d/13c_eYG2v4wNnp9RIhE_gXCSTvEw_i_HQzK7djEsSOjw/

[Makefile] Run `upload-code` before `training`

---

setup.cfg
{{cookiecutter.project_slug}}/setup.cfg

1. ignore files
2. line length 88
3. see more in PR
Code style will look more like [`neuromation client`](https://github.com/neuromation/platform-client-python/).
as requested here: https://docs.google.com/document/d/13c_eYG2v4wNnp9RIhE_gXCSTvEw_i_HQzK7djEsSOjw/

[Template] Change rules for make lint

---

.circleci/config.yml
tests/e2e/helpers/runners.py
tests/e2e/test_e2e_template.py

1. certifi outdated
2. pattern for tensorboard test
3. bonus: small bug in tests

Fix tests after image update

---

tests/e2e/configuration.py
tests/e2e/helpers/runners.py
tests/e2e/test_e2e_template.py

cleanup prior to https://github.com/neuromation/cookiecutter-neuro-project/pull/245/

[tests] Minor: tests cleanup

---

tests/e2e/configuration.py
tests/e2e/conftest.py
tests/e2e/helpers/runners.py
tests/e2e/test_e2e_template.py
tests/e2e/test_e2e_tools_auth.py

1. move some e2e tests to another file
2. most commands: verbose=True
Preliminary step to W&B integration.

[tests] Refactor tests

---

.circleci/config.yml

will increase our control on Template stability.
**WARNING**: Should be merged after [`neuro`-side integration](https://github.com/neuromation/platform-client-python/pull/1248) is merged and released.

[testing] Nightly builds for master, hourly builds for release

---

tests/e2e/conftest.py
tests/e2e/test_e2e_template.py
tests/e2e/test_e2e_tools_auth.py

1. remove extra key files decryption for unnecessary tests
2. no unnecessary `try_except_finally` decorator

[tests] Small test cleanup

---

.circleci/config.yml

revert PR https://github.com/neuromation/cookiecutter-neuro-project/pull/253
somehow after it was merged, no nightly tests were running
closes https://github.com/neuromation/cookiecutter-neuro-project/issues/273

[tests] Revert nigthly testing switch to release branch

---

{{cookiecutter.project_slug}}/README.md

closes https://github.com/neuromation/cookiecutter-neuro-project/issues/241

[Readme] Add reference to remote debugging instructions

---

{{cookiecutter.project_slug}}/.gitignore

1. Add missing entries (Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/258, https://github.com/neuromation/cookiecutter-neuro-project/issues/259)
2. Update default Python .gitignore taken from https://github.com/github/gitignore/blob/master/Python.gitignore
3. State that those default entries are taken from that file (closes https://github.com/neuromation/cookiecutter-neuro-project/issues/170)

[Template] Rework .gitignore

---

LICENSE

closes https://github.com/neuromation/cookiecutter-neuro-project/issues/266

[Template] Change license MIT -> Apache 2.0

---

tests/e2e/test_e2e_template.py
tests/e2e/test_e2e_tools_auth.py
{{cookiecutter.project_slug}}/Makefile
{{cookiecutter.project_slug}}/README.md

Closes  https://github.com/neuromation/cookiecutter-neuro-project/issues/282 and https://github.com/neuromation/cookiecutter-neuro-project/issues/247

[Makefile] Shorten TRAINING_COMMAND env var

---

{{cookiecutter.project_slug}}/Makefile

Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/121

[Template] Install pip packages with --no-cache-dir

---

tests/e2e/test_e2e_template.py
tests/e2e/test_e2e_tools_auth.py
{{cookiecutter.project_slug}}/Makefile
{{cookiecutter.project_slug}}/requirements.txt

Out of scope of current iteration, but might be still useful.

[Makefile] Add jupyter-lab target

---

tests/e2e/helpers/runners.py
tests/e2e/helpers/utils.py
tests/e2e/test_e2e_template.py
tests/e2e/test_e2e_tools_auth.py

Reduce number of test functions by converting decorator `try_except_finally` to decorator-and-contextmanager `finalize`

[tests] Simplify tests

---

{{cookiecutter.project_slug}}/Makefile

Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/263

[Makefile] Pass env var PYTHONHOME to develop job

---

tests/e2e/test_e2e_template.py
tests/e2e/test_e2e_tools_auth.py

temporarily patches https://github.com/neuromation/cookiecutter-neuro-project/issues/280

[tests] Give flaky tests on `neuro exec` 2 attempts

---

tests/e2e/test_e2e_template.py
{{cookiecutter.project_slug}}/.gitignore
{{cookiecutter.project_slug}}/Makefile

Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/288

[Makefile] Stream tqdm logs for all training jobs via `neuro exec`

---

{{cookiecutter.project_slug}}/Makefile

To fix typo in `Makefile` and resolve #318

[Makefile] Fixed develop timeout parameter name

---

{{cookiecutter.project_slug}}/Makefile

Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/328

[Makefile] Use versioned base env

---

{{cookiecutter.project_slug}}/Makefile

Internal functionality, thus is not covered with tests.

[Makefile] Upgrade the template, reverting the user content

---

{{cookiecutter.project_slug}}/Makefile

part of https://github.com/neuromation/cookiecutter-neuro-project/pull/343

[Makefile] Get rid of env vars: PIP, APT

---

tests/e2e/test_e2e_template.py
{{cookiecutter.project_slug}}/Makefile

Cleanup:
1. `${VAR}` -> `$(VAR)`
2. `$${PWD} -> $$PWD`

[Makefile] Replace all vars ${VAR} to $(VAR)

---

{{cookiecutter.project_slug}}/Makefile

Error: sometimes project is `uncategorized` even if local `wandb` has initialized a project.

[Makefile] Fix wandb hypertrain

---

requirements-dev.txt
tests/e2e/configuration.py
tests/e2e/conftest.py
tests/e2e/test_e2e_template.py
{{cookiecutter.project_slug}}/requirements.txt

1. In Template, put `neuromation==20.3.20` to `requirements.txt` (version should be fixed for stability)
2. Bump pip versions in `requirements-dev.txt`

Install neuromation fixed version

---

{{cookiecutter.project_slug}}/Makefile

closes https://github.com/neuromation/cookiecutter-neuro-project/issues/185

[Makefile] Simplify env var: `CUSTOM_ENV_NAME`, `BSSE_ENV_NAME`

---

tests/e2e/test_e2e_template.py
{{cookiecutter.project_slug}}/Makefile

Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/228

[Makefile] Rename targets `format`, `lint`: use postfix `-local`

---

{{cookiecutter.project_slug}}/Makefile

Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/178

[Makefile] Change `--notebooks-dir` for `make jupyter`

---

{{cookiecutter.project_slug}}/Makefile

Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/351

[Makefile] Use tensorflow image to run tensorboard

---

{{cookiecutter.project_slug}}/Makefile

Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/172 and https://github.com/neuromation/cookiecutter-neuro-project/issues/110

[Makefile] Upload/download only notebooks, improve readability

---

tests/e2e/configuration.py
tests/e2e/conftest.py
tests/e2e/helpers/runners.py
tests/e2e/test_e2e_template.py
{{cookiecutter.project_slug}}/.neuro.toml

Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/93

[Template] Exclude cache files while uploading files on Storage

---

{{cookiecutter.project_slug}}/Makefile

closes https://github.com/neuromation/cookiecutter-neuro-project/issues/227

[Makefile] Add argument RUN_EXTRA to all targets that run a job

---

{{cookiecutter.project_slug}}/Makefile

Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/124, improves how env var are organized.

[Makefile] Move env variables, improve their comments

---

.azure-pipelines/stage-e2e.yml
tests/e2e/configuration.py
tests/e2e/conftest.py
tests/e2e/test_e2e_template.py
tests/e2e/test_e2e_tools_auth.py
{{cookiecutter.project_slug}}/Makefile

they are very flaky. If needed, we can return back in Git history to restore them.

Drop flaky tests on W&B and hypertrain

---

Makefile
tests/e2e/conftest.py
tests/e2e/helpers/runners.py
tests/e2e/test_e2e_template.py
tests/e2e/test_e2e_tools_auth.py
{{cookiecutter.project_slug}}/Makefile

[Makefile] Secrets support

---

{{cookiecutter.project_slug}}/Makefile
{{cookiecutter.project_slug}}/requirements.txt

Remove hypertrain

---

{{cookiecutter.project_slug}}/HELP.md

Replace outdated docs with links to Neu.ro documentation for:
* GCP access
* AWS access
* Using Weights & Biases

Update readme for Secrets

---

tests/e2e/test_e2e_template.py

Fix tests on master

---

LICENSE
cookiecutter.json
hooks/post_gen_project.py
hooks/pre_gen_project.py
{{cookiecutter.project_slug}}/.neuro/live.yml

**WARNING**: This PR is to branch `ys/neuro-flow-migration`

Neuro flow migration: Fix tests and cleanup

---

{{cookiecutter.project_slug}}/.neuro/live.yml

Since we need to explicitly define it.
This input was added [here](https://github.com/neuro-actions/jupyter/pull/1), more discussions are [here](https://github.com/neuro-actions/jupyter/pull/2#issuecomment-734798842).

Add the preset into jupyter action args.

---

Makefile
README.md
RELEASE.md
tests/cookiecutter.yaml
{{cookiecutter.project_slug}}/.gitignore
{{cookiecutter.project_slug}}/.neuro/live.yml
{{cookiecutter.project_slug}}/Dockerfile

1. Replace `neuromation` with `neuro-inc` / `neuro` where applicable
2. Make config files writeable and add them under source control
3. Add `v1` tag for the image

Update template for neu.ro

---

CHANGELOG.D/458.feature
{{cookiecutter.project_slug}}/.neuro/live.yml

Pin neuro-actions' versions

---

{{cookiecutter.project_dir}}/.neuroignore

several folks asked about it: @johngull and one guy from the Synthesis team

Add data to .neuroignore

---

CHANGELOG.D/596.feature
Makefile
hooks/post_gen_project.py
pytest.ini
requirements/dev.txt
setup.cfg
tests/unit/test_bake_project.py

Add username and role generator
