neuro-inc/cookiecutter-neuro-project

- cookiecutter.json
- {{cookiecutter.project_slug}}/Makefile
Closes #30. 
@mariyadavydova Would you mind updating readme with relevant info? It should say something along the lines "HTTP authentication for your jobs is enabled by default. Set `DISABLE_HTTP_AUTH` to `True` in Makefile to disable. This is dangerous bla-bla-bla".
> Enable HTTP authentication by default

- tests/e2e/configuration.py
Currently we install via pip:
`PACKAGES_PIP_CUSTOM = ["aiohttp==3.6", "aiohttp_security==0.4.0", "neuromation"]`
Since today night, when `neuromation==19.9.23` that depends on `aiohttp==3.6.1` was released, we got an error:
`ERROR: neuromation 19.9.23 has requirement aiohttp>=3.6.1, but you'll have aiohttp 3.6.0 which is incompatible.`
This error is detected with pattern `r"ERROR[^:]*: "` and the test on `make setup` fails.
> Fix error with testing packages version conflict

- tests/e2e/configuration.py
- tests/e2e/conftest.py
- tests/e2e/test_e2e_template.py
- tests/e2e/utils.py
otherwise any 2 builds interfere and break each other
> Generate unique project names for each test run

- .circleci/config.yml
- tests/e2e/conftest.py
1. Do not cleanup running jobs as fixture (otherwise we loose output on CI)
2. Remove `~/.nmrc` as CI instruction, not as fixture
> Better cleanup

- cleanup_jobs.py
this is the last problem of test helpers I know that cause cross-build interference.
> Do not kill all the user's jobs during cleanup

- tests/e2e/configuration.py
- tests/e2e/test_e2e_template.py
Pattern `Copy 'file://.*{file_name}'` does not work: if the path is too long, the word `Copy` is followed by a new line char.
> Fix patterns for copying files

- Makefile
- tests/e2e/configuration.py
- tests/e2e/helpers/runners.py
- tests/e2e/test_e2e_template.py
as discussed with @asvetlov , we should retry only tests that usually fail. For now, it's `make setup`. 
NOTE: during `make setup`, the most unstable part is `neuro save`. Firstly, I was planning to split `make setup` into few separate targets so that to test them individually (and re-run only `neuro save` part), but this is non-fair testing. So better test exact `make setup` and accept the overhead.
TODO: change the retry strategy: retry only when certain patterns found and break otherwise
> Retry only usually-failing tests 

- Makefile
- cookiecutter.json
- hooks/pre_gen_project.py
- tests/e2e/configuration.py
- tests/unit/test_bake_project.py
- {{cookiecutter.project_slug}}/Makefile
We use project_slug for the repo name (which is usually with dashes, not underscores) and in job names (where we can't even use underscores).
> project_slug with dashes instead of underscores

- tests/e2e/test_e2e_template.py
because it's pointless to continue if `make setup` failed.
> Abort tests if `make setup` failed

- tests/e2e/configuration.py
Getting the following errors locally:
```
assert "Name: neuromation" in run("pip show neuromation", verbose=False)
E   assert 'Name: neuromation' in "ame: neuromation\r\nVersion: 19.9.23\r\nSummary: Neuromation Platform API client\r\nHome-page: https://neuromation.io... version 19.3.1 is available.\r\nYou should consider upgrading via the 'pip install --upgrade pip' command.\x1b[0m\r\n"
E    +  where "ame: neuromation\r\nVersion: 19.9.23\r\nSummary: Neuromation Platform API client\r\nHome-page: https://neuromation.io... version 19.3.1 is available.\r\nYou should consider upgrading via the 'pip install --upgrade pip' command.\x1b[0m\r\n" = run('pip show neuromation', verbose=False)
```
seems like the first char didn't get into the buffer.
> Increase pexpect buffer for test runners

- .circleci/config.yml
- tests/e2e/configuration.py
- tests/e2e/helpers/runners.py
- tests/e2e/helpers/utils.py
- tests/e2e/test_e2e_template.py
- {{cookiecutter.project_slug}}/Makefile
The story: tests on dev [succeed](https://circleci.com/gh/neuromation/cookiecutter-neuro-project/673) and tests on staging [fail](https://circleci.com/gh/neuromation/cookiecutter-neuro-project/674). The symptoms there are that on dev, test `make upload-code` [passes](https://673-204585942-gh.circle-artifacts.com/0/ouptut/output_test-project-004b0540.log) the check of `neuro ls` (search for `'file:///.../test-cookiecutter0/test-project-004b0540/modules' DONE` -- there's no errors there), however on staging, this test [fails](https://674-204585942-gh.circle-artifacts.com/0/ouptut/output_test-project-6d648641.log) that check (search for `'file:///.../test-cookiecutter0/test-project-6d648641/modules' DONE`). 
There are 3 possible sources of the problem:
1. a back-end problem. Not confirmed …
> Fix uploading: keep directories

- tests/e2e/test_e2e_template.py
- {{cookiecutter.project_slug}}/Makefile
Thanks @AlekseySh for pointing out this problem: by default, filebrowser requires credentials `admin:admin`
> Drop filebrowser authentication

- {{cookiecutter.project_slug}}/Makefile
Great catch by @atselousov!
Sorry @mariyadavydova for asking you one day to change the command for `make setup` job from `sleep infinity` to `sleep 1h` -- it appeared to be that `docker commit` (which is used in `neuro save`, which is used by `make setup`) sets the `CMD` passed to the container (in this case, `sleep 1h`) to the new image. Then, if one starts a job from this newly created image, and does not specify the command (`neuro run image:my-base-image`), the command will be `sleep 1h`!
> Fix CMD for user's base image

- tests/e2e/cleanup.sh
Close https://github.com/neuromation/cookiecutter-neuro-project/issues/168
Unfortunately, I haven't understood why `neuro ls` hangs on `dev` builds only -- when I run it locally, everything's fine. 
Example: The output 
```
abc
test-project-07a57d85
test-project-11e6101b
test-project-2a9dc11a
test-project-3172bc9b
test-project-32ea98d7
test-project-34dc3cf5
test-project-466b171f
test-project-59008fe9
test-project-6a013ca5
test-project-71cbfd88
test-project-77e20d13
test-project-92af88de
test-project-a07d7b4a
test-project-b011c804
test-project-b8c20f0d
test-project-e6f127c8
test-project-ed18e3ff
test_project_6ee04879
test_project_76a203c0
test_project_7b22dc52
test_project_7e321888
try-comet-ml
```
is printed until `test_project_7e321888`, then it hangs (so `try-comet-ml` is not printed) …
> Fix e2e test cleanup hang

- Makefile
- tests/e2e/test_e2e_template.py
- {{cookiecutter.project_slug}}/Makefile
- {{cookiecutter.project_slug}}/README.md
`TRAINING_MACHINE_TYPE` -> `PRESET`:
1. I always forget the longer name
2. it looks bulky: `make jupyter TRAINING_MACHINE_TYPE=cpu-small`, instead, `make jupyter PRESET=cpu-small` looks more ideomatically correct w.r.t. `neuro` terminology.
Please note: simultaneously withi this PR, **[docs](https://github.com/neuromation/platform-web/search?q=TRAINING_MACHINE_TYPE&unscoped_q=TRAINING_MACHINE_TYPE) must be fixed!**
> [Makefile] Rename long variable for preset

- {{cookiecutter.project_slug}}/Makefile
1. disable timeout for `make training`: it may last more than 1 day.
2. enable timeout 1 hour for `make setup`
3. enable explicit timeout 1 day for all other targets
> [Makefile] Set up job timeouts

- tests/e2e/configuration.py
- tests/e2e/test_e2e_template.py
test for `make train` flakes: we await status `succeeded`, but sometimes `neuro` sees `running` instead:
https://circleci.com/gh/neuromation/cookiecutter-neuro-project/1209
> Fix flaky test

- tests/e2e/configuration.py
- tests/e2e/conftest.py
1. Make env var shorter so that it's easier to remember (when using this functionality, I always need to go to `configuration.py` to remember `EXISTING_PROJECT_SLUG`)
2. add a bit logging info -- just for clarity
> [tests] Minor: simplify running tests against existing projects

- {{cookiecutter.project_slug}}/requirements.txt
Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/283
Before, `tqdm` in `requirements.txt` was just an example. 
1. We'll install it to the base image
2. No tests rely on it.
Question: Should we pre-install these dependencies also to the base image in order to shorten `make setup` time?
> [Template] Add dependencies mypy+isort+black+flake

- {{cookiecutter.project_slug}}/Makefile
1. Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/242
2. Runs `neuro mkdir` with parameter `--parent` during `make setup`
> [Makefile] Fix `make setup` UX issue

- Makefile
- {{cookiecutter.project_slug}}/Makefile
See https://github.com/neuromation/neuro-base-environment/issues/81
No need to support (keep them pre-pulled on nodes) multiple tags:
1. we'll keep backward compatibility of the base image
2. we'll update `latest` image manually, only stable image -- not on every change
3. base image is used only in `make setup`: so updated `latest` base image won't affect existing user's custom base images.
> [Makefile] Use latest base image

- {{cookiecutter.project_slug}}/Makefile
After https://github.com/neuromation/platform-client-python/issues/1272 was released, killing targets started to fail. This is a very quick, fast and dirty fix to make them work again.
> Quick fix for `neuro kill`

- .circleci/config.yml
- Makefile
- requirements-dev.txt
- tests/e2e/configuration.py
- tests/e2e/conftest.py
- tests/e2e/helpers/logs.py
- tests/e2e/helpers/runners.py
- tests/e2e/helpers/utils.py
- tests/e2e/test_e2e_template.py
- tests/e2e/test_e2e_tools_auth.py
Important changes **in bold**.
1. **Add missing doctests on test runners (they were not run before)**
2. Fix a mistake in test runners (error patterns were not asserted)
3. Run unit test in a temp directory instead of `..` (closes https://github.com/neuromation/cookiecutter-neuro-project/issues/126)
4. Install less custom pip and apt packages (first, there were pip conflicts in versions of neuromation and aiohttp, second, there's no need to install many packages)
5. Fix import fernet -> cryptography (somehow fernet stopped working)
6. Improve logging: print env vars because they matter
7. Add test functionality to skip default error pattern search (for tests that test failure scenarios)
8. **Add test functionality to re-run only if a certain error substring was found** (for now, it's only …
> [tests] Stabilize tests

- cookiecutter.json
default project slug `name-of-the-project` is too long, for this, jobs run with hypertrain fail of too long job name.
> [Template] Change default project name

- tests/e2e/test_e2e_template.py
https://dev.azure.com/neuromation/cookiecutter-neuro-project/_build/results?buildId=2533&view=logs&j=63c7865a-3588-542b-203b-b65599712d82&t=12cdcf0a-6d87-5aaf-034b-f05b1d42dfa8
```
2020-02-27T21:10:38.0826193Z tests/e2e/test_e2e_template.py::test_gpu_available 
2020-02-27T21:10:38.0828186Z 00:00.001 inf e2e: Measuring time for command: `make develop PRESET=gpu-small`
2020-02-27T21:10:38.0830711Z 00:00.001 inf e2e: Attempt 1/3 (will re-run for any of: ['stale NFS file handle'])
2020-02-27T21:10:38.0832054Z 00:00.001 inf e2e: <<< make develop PRESET=gpu-small
2020-02-27T21:10:38.1083867Z 00:00.026 inf e2e: Search patterns: ['Status:[^\\n]+running']
2020-02-27T21:10:55.1898089Z 00:17.107 inf e2e: Found expected pattern: 'Status:[^\\n]+running'
2020-02-27T21:10:55.2582025Z 00:17.176 inf e2e: …
```
> [tests] Fix test on Linux

- Makefile
Follow-up of https://github.com/neuromation/cookiecutter-neuro-project/pull/359 , closes https://github.com/neuromation/cookiecutter-neuro-project/issues/347
> [Makefile] Complete normalizing braces

- tests/e2e/test_e2e_template.py
- {{cookiecutter.project_slug}}/HELP.md
- {{cookiecutter.project_slug}}/Makefile
- {{cookiecutter.project_slug}}/requirements.txt
I always forget how it's called. `N_JOBS` is shorter and easier to remember.
> [Makefile] Use shorter name for N_HYPERPARAM_JOBS argument

- {{cookiecutter.project_slug}}/.gitignore
- {{cookiecutter.project_slug}}/Makefile
1. Add `config/*.yml` to .gitignore
2. Add ssh key generation during `make setup`
These two steps simplify NNI tutorial, because this allows us not to minimize changes in template files when use wants to enable NNI.
> Minor improvements to simplify NNI integration

- {{cookiecutter.project_slug}}/HELP.md
- {{cookiecutter.project_slug}}/Makefile
When [debugging](https://github.com/neuromation/ml-recipe-project-zero/pull/1) `make train` in Project Zero, I felt annoyance while waiting for all directories to sync before the job starts (and usually fails). So I'd like to have control to temporarily disable sync.
Closes https://github.com/neuromation/cookiecutter-neuro-project/issues/118 with a compromise solution: 
```
$ make train  # syncs
$ make train SYNC=''  # does not sync
$ export SYNC=''
$ make train  # does not sync
```
> [Makefile] Sync directories optionally

- .azure-pipelines/stage-e2e.yml
- {{cookiecutter.project_slug}}/.gitignore
- {{cookiecutter.project_slug}}/Makefile
Problems:
1. some macs don't have `/proc/self/fd/2`
2. some `wandb` printed `Create sweep with ID: ...` instead of `Created sweep with ID: ...` so grep was failing
3. removed `grep` in piped operation since even if it failed, the pipe execution was continuing to `awk`
> [Makefile] Stabilize W&B Hypertrain + Set up CI for MacOS

- tests/e2e/helpers/utils.py
- tests/e2e/test_e2e_template.py
Sometimes `make clean-results` test flake: 
https://dev.azure.com/neuromation/cookiecutter-neuro-project/_build/results?buildId=3744&view=results
Perhaps, the reason is unsynchronized NFS. Anyways, we don't need these tests to be so exhaustive, we just need to check that the targets didn't fail with non-zero exit code.
> [tests] Fix flaky cleanup tests

- {{cookiecutter.project_slug}}/Makefile
when working with jupyter, its state is not always sync'ed to the storage (you need to press Ctrl+S to save it). So when `upload-notebooks` is called automatically as a dependency for another command, you might overwrite the remote version of the notebook with the outdated local version.
Another use-case is when you open a jupyter locally and it changes its modification date.
> [Makefile] No upload-notebooks before each command

- tests/e2e/test_e2e_template.py
It [flakes](https://dev.azure.com/neuromation/cookiecutter-neuro-project/_build/results?buildId=4339&view=logs&j=4db9e34a-a06b-5cd0-72b0-15645ff85cca&t=a49aa7d9-d43a-5ff3-059f-2ed74bab9163) a lot:
```
neuro --verbose --show-traceback --color=no run --tag=build-4339 \
\
--name filebrowser-test-project-4c33982c \
--tag "target:filebrowser" --tag "kind:project" --tag "project:test-project-4c33982c" --tag "project-id:neuro-project-b77256af" \
--preset cpu-small \
--http 80 \
--no-http-auth \
--browse \
--life-span=1d \
--volume storage:test-project-4c33982c:/srv:rw \
filebrowser/filebrowser:latest \
--noauth
Using preset 'cpu-small': Preset(cpu=1, memory_mb=4096, is_preemptible=False, gpu=None, gpu_model=None, tpu_type=None, tpu_software_version=None)
Using image …
```
> Drop filebrowser test

- {{cookiecutter.project_slug}}/.neuro/live.yml
Use `cpu-small` preset for image builds instead of `cpu-micro` by default
> Speed up image build
